# Generated by Django 5.1.7 on 2025-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="Item_image",
            field=models.CharField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fpatelsfoodandchaat.co.uk%2Fmenu%2F&psig=AOvVaw33lf8X-I08o9XBGuR7dzL2&ust=1743691641010000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMCeh-PLuYwDFQAAAAAdAAAAABAE",
                max_length=500,
            ),
        ),
    ]
