# Generated by Django 5.1.7 on 2025-04-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Item_image",
            field=models.CharField(
                default="https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Pizza-3007395.jpg/1200px-Pizza-3007395.jpg",
                max_length=500,
            ),
        ),
    ]
