# Generated by Django 5.1.7 on 2025-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_alter_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="Item_image",
            field=models.CharField(
                default="https://www.shutterstock.com/image-photo/restaurant-blackboard-announcing-reopening-after-600nw-1735273409.jpg",
                max_length=500,
            ),
        ),
    ]
